# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pymol_rpc_pb2 as pymol__rpc__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pymol_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PyMolRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/PyMolRPC/Ping',
                request_serializer=pymol__rpc__pb2.Empty.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Do = channel.unary_unary(
                '/PyMolRPC/Do',
                request_serializer=pymol__rpc__pb2.CommandRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Label = channel.unary_unary(
                '/PyMolRPC/Label',
                request_serializer=pymol__rpc__pb2.LabelRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Sphere = channel.unary_unary(
                '/PyMolRPC/Sphere',
                request_serializer=pymol__rpc__pb2.SphereRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Cylinder = channel.unary_unary(
                '/PyMolRPC/Cylinder',
                request_serializer=pymol__rpc__pb2.CylinderRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.LoadPDB = channel.unary_unary(
                '/PyMolRPC/LoadPDB',
                request_serializer=pymol__rpc__pb2.LoadMolRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.LoadMolBlock = channel.unary_unary(
                '/PyMolRPC/LoadMolBlock',
                request_serializer=pymol__rpc__pb2.LoadMolRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.LoadFile = channel.unary_unary(
                '/PyMolRPC/LoadFile',
                request_serializer=pymol__rpc__pb2.LoadFileRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.LoadSurface = channel.unary_unary(
                '/PyMolRPC/LoadSurface',
                request_serializer=pymol__rpc__pb2.LoadSurfaceRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetNames = channel.unary_unary(
                '/PyMolRPC/GetNames',
                request_serializer=pymol__rpc__pb2.GetNamesRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.GetNamesResponse.FromString,
                _registered_method=True)
        self.GetAtomCoords = channel.unary_unary(
                '/PyMolRPC/GetAtomCoords',
                request_serializer=pymol__rpc__pb2.GetAtomCoordsRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.GetAtomCoordsResponse.FromString,
                _registered_method=True)
        self.DeleteObject = channel.unary_unary(
                '/PyMolRPC/DeleteObject',
                request_serializer=pymol__rpc__pb2.ObjectRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteAll = channel.unary_unary(
                '/PyMolRPC/DeleteAll',
                request_serializer=pymol__rpc__pb2.Empty.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Center = channel.unary_unary(
                '/PyMolRPC/Center',
                request_serializer=pymol__rpc__pb2.CenterRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Zoom = channel.unary_unary(
                '/PyMolRPC/Zoom',
                request_serializer=pymol__rpc__pb2.ZoomRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Rotate = channel.unary_unary(
                '/PyMolRPC/Rotate',
                request_serializer=pymol__rpc__pb2.RotateRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/PyMolRPC/Move',
                request_serializer=pymol__rpc__pb2.MoveRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Hide = channel.unary_unary(
                '/PyMolRPC/Hide',
                request_serializer=pymol__rpc__pb2.ShowHideRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Show = channel.unary_unary(
                '/PyMolRPC/Show',
                request_serializer=pymol__rpc__pb2.ShowHideRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Color = channel.unary_unary(
                '/PyMolRPC/Color',
                request_serializer=pymol__rpc__pb2.ColorRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetTransparency = channel.unary_unary(
                '/PyMolRPC/SetTransparency',
                request_serializer=pymol__rpc__pb2.TransparencyRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Select = channel.unary_unary(
                '/PyMolRPC/Select',
                request_serializer=pymol__rpc__pb2.SelectionRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteSelection = channel.unary_unary(
                '/PyMolRPC/DeleteSelection',
                request_serializer=pymol__rpc__pb2.SelectionRequest.SerializeToString,
                response_deserializer=pymol__rpc__pb2.StatusResponse.FromString,
                _registered_method=True)


class PyMolRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Do(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Label(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sphere(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cylinder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadMolBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSurface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAtomCoords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """Backward compatibility methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Center(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Zoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Show(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Color(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTransparency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSelection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PyMolRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=pymol__rpc__pb2.Empty.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Do': grpc.unary_unary_rpc_method_handler(
                    servicer.Do,
                    request_deserializer=pymol__rpc__pb2.CommandRequest.FromString,
                    response_serializer=pymol__rpc__pb2.CommandResponse.SerializeToString,
            ),
            'Label': grpc.unary_unary_rpc_method_handler(
                    servicer.Label,
                    request_deserializer=pymol__rpc__pb2.LabelRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Sphere': grpc.unary_unary_rpc_method_handler(
                    servicer.Sphere,
                    request_deserializer=pymol__rpc__pb2.SphereRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Cylinder': grpc.unary_unary_rpc_method_handler(
                    servicer.Cylinder,
                    request_deserializer=pymol__rpc__pb2.CylinderRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'LoadPDB': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPDB,
                    request_deserializer=pymol__rpc__pb2.LoadMolRequest.FromString,
                    response_serializer=pymol__rpc__pb2.CommandResponse.SerializeToString,
            ),
            'LoadMolBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMolBlock,
                    request_deserializer=pymol__rpc__pb2.LoadMolRequest.FromString,
                    response_serializer=pymol__rpc__pb2.CommandResponse.SerializeToString,
            ),
            'LoadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadFile,
                    request_deserializer=pymol__rpc__pb2.LoadFileRequest.FromString,
                    response_serializer=pymol__rpc__pb2.CommandResponse.SerializeToString,
            ),
            'LoadSurface': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSurface,
                    request_deserializer=pymol__rpc__pb2.LoadSurfaceRequest.FromString,
                    response_serializer=pymol__rpc__pb2.CommandResponse.SerializeToString,
            ),
            'GetNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNames,
                    request_deserializer=pymol__rpc__pb2.GetNamesRequest.FromString,
                    response_serializer=pymol__rpc__pb2.GetNamesResponse.SerializeToString,
            ),
            'GetAtomCoords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAtomCoords,
                    request_deserializer=pymol__rpc__pb2.GetAtomCoordsRequest.FromString,
                    response_serializer=pymol__rpc__pb2.GetAtomCoordsResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=pymol__rpc__pb2.ObjectRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteAll': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAll,
                    request_deserializer=pymol__rpc__pb2.Empty.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Center': grpc.unary_unary_rpc_method_handler(
                    servicer.Center,
                    request_deserializer=pymol__rpc__pb2.CenterRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Zoom': grpc.unary_unary_rpc_method_handler(
                    servicer.Zoom,
                    request_deserializer=pymol__rpc__pb2.ZoomRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Rotate': grpc.unary_unary_rpc_method_handler(
                    servicer.Rotate,
                    request_deserializer=pymol__rpc__pb2.RotateRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=pymol__rpc__pb2.MoveRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Hide': grpc.unary_unary_rpc_method_handler(
                    servicer.Hide,
                    request_deserializer=pymol__rpc__pb2.ShowHideRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Show': grpc.unary_unary_rpc_method_handler(
                    servicer.Show,
                    request_deserializer=pymol__rpc__pb2.ShowHideRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Color': grpc.unary_unary_rpc_method_handler(
                    servicer.Color,
                    request_deserializer=pymol__rpc__pb2.ColorRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'SetTransparency': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTransparency,
                    request_deserializer=pymol__rpc__pb2.TransparencyRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=pymol__rpc__pb2.SelectionRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteSelection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSelection,
                    request_deserializer=pymol__rpc__pb2.SelectionRequest.FromString,
                    response_serializer=pymol__rpc__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PyMolRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PyMolRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PyMolRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Ping',
            pymol__rpc__pb2.Empty.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Do(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Do',
            pymol__rpc__pb2.CommandRequest.SerializeToString,
            pymol__rpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Label(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Label',
            pymol__rpc__pb2.LabelRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sphere(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Sphere',
            pymol__rpc__pb2.SphereRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cylinder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Cylinder',
            pymol__rpc__pb2.CylinderRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/LoadPDB',
            pymol__rpc__pb2.LoadMolRequest.SerializeToString,
            pymol__rpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadMolBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/LoadMolBlock',
            pymol__rpc__pb2.LoadMolRequest.SerializeToString,
            pymol__rpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/LoadFile',
            pymol__rpc__pb2.LoadFileRequest.SerializeToString,
            pymol__rpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSurface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/LoadSurface',
            pymol__rpc__pb2.LoadSurfaceRequest.SerializeToString,
            pymol__rpc__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/GetNames',
            pymol__rpc__pb2.GetNamesRequest.SerializeToString,
            pymol__rpc__pb2.GetNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAtomCoords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/GetAtomCoords',
            pymol__rpc__pb2.GetAtomCoordsRequest.SerializeToString,
            pymol__rpc__pb2.GetAtomCoordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/DeleteObject',
            pymol__rpc__pb2.ObjectRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/DeleteAll',
            pymol__rpc__pb2.Empty.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Center(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Center',
            pymol__rpc__pb2.CenterRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Zoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Zoom',
            pymol__rpc__pb2.ZoomRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Rotate',
            pymol__rpc__pb2.RotateRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Move',
            pymol__rpc__pb2.MoveRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Hide',
            pymol__rpc__pb2.ShowHideRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Show(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Show',
            pymol__rpc__pb2.ShowHideRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Color(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Color',
            pymol__rpc__pb2.ColorRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTransparency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/SetTransparency',
            pymol__rpc__pb2.TransparencyRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/Select',
            pymol__rpc__pb2.SelectionRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSelection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PyMolRPC/DeleteSelection',
            pymol__rpc__pb2.SelectionRequest.SerializeToString,
            pymol__rpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
