#A* -------------------------------------------------------------------
#B* This file contains source code for running a GitHub automation
#-* related to the build process of the PyMOL computer program
#C* Copyright 2025 by Martin Urban.
#D* -------------------------------------------------------------------
#E* It is unlawful to modify or remove this copyright notice.
#F* -------------------------------------------------------------------
#G* Please see the accompanying LICENSE file for further information.
#H* -------------------------------------------------------------------
#I* Additional authors of this source file include:
#-*
#-*
#-*
#Z* -------------------------------------------------------------------
name: Build Wheels

on:
  push:
    branches:
      - update-to-3.0.2.X

env:
  VCPKG_ROOT: ${{ github.workspace }}/vendor/vcpkg

jobs:
  # ----- Windows build section
  build-windows:
    env:
      WIN_ARCH: ${{ matrix.win_arch }}
      CMAKE_GENERATOR: Visual Studio 17 2022
      CMAKE_GENERATOR_TOOLSET: v143
    strategy:
      fail-fast: false
      matrix:
        win_arch: ['x86', 'x64']
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Initialize vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git vendor/vcpkg

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'

      - name: Sync Python environment
        run: uv sync --locked --no-install-project
        shell: cmd

      - name: Bootstrap vcpkg
        run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.bat -disableMetrics

      - name: Last build environment setup steps
        run: uv run --locked --no-sync python pymakefile.py setup_dev_env
        shell: cmd

      - name: Build x86 C extension
        if: ${{ matrix.win_arch == 'x86' }}
        run: |
          ${{ env.VCPKG_ROOT }}/vcpkg install --triplet=x86-windows-static
          set WIN_ARCH=x86
          uv run --locked --no-sync python pymakefile.py build_wheels platform=windows archs=x86
        shell: cmd

      - name: Build x64 C extension
        if: ${{ matrix.win_arch == 'x64' }}
        run: |
          ${{ env.VCPKG_ROOT }}/vcpkg install --triplet=x64-windows-static
          set WIN_ARCH=x64
          uv run --locked --no-sync python pymakefile.py build_wheels platform=windows archs=AMD64
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyMOL-wheel-Windows-${{ matrix.win_arch }}-3.11
          path: ./wheelhouse/*.whl
  # --- end

  # ----- macOS build section
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Initialize vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git vendor/vcpkg

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync Python environment
        run: uv sync --locked --no-install-project

      - name: Bootstrap vcpkg
        run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.sh -disableMetrics

      - name: Install vcpkg dependencies
        run: |
          ${{ env.VCPKG_ROOT }}/vcpkg install

      - name: Last build environment setup steps
        run: ARCH=$(uname -m) uv run --locked --no-sync python pymakefile.py setup_dev_env

      - name: Build C extension
        run: |
          export ARCH=$(uname -m)
          export MACOSX_DEPLOYMENT_TARGET=12.0
          uv run --locked --no-sync python pymakefile.py build_wheels

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyMOL-wheel-${{ matrix.os }}-3.11
          path: ./wheelhouse/*.whl
  # --- end

  # ----- GNU Linux build section
  build-gnu-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential libxmu-dev libxi-dev libgl-dev libglew-dev libpng-dev libfreetype6-dev libxml2-dev libmsgpack-dev libglm-dev libnetcdf-dev linux-libc-dev autoconf perl

      - name: Initialize vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git vendor/vcpkg

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sync Python environment
        run: uv sync --locked --no-install-project

      - name: Bootstrap vcpkg
        run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.sh -disableMetrics

      - name: Install vcpkg dependencies
        run: |
          ${{ env.VCPKG_ROOT }}/vcpkg install

      - name: Last build environment setup steps
        run: uv run --locked --no-sync python pymakefile.py setup_dev_env

      - name: Build C extension
        run: uv run --locked --no-sync python pymakefile.py build_wheels

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyMOL-wheel-GNU-Linux-3.11
          path: ./wheelhouse/*.whl
  # --- end
